// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-west-2",
//     "aws_cognito_identity_pool_id": "us-west-2:51ae6690-02e2-4b44-ae0e-b19e76e71cf6",
//     "aws_cognito_region": "us-west-2",
//     "aws_user_pools_id": "us-west-2_cnmvDtQtS",
//     "aws_user_pools_web_client_id": "k1m8k2uejmb3ii6jt27fd1fio",
//     "oauth": {}
// };

const awsmobile = {

        identityPoolId: 'us-west-2:51ae6690-02e2-4b44-ae0e-b19e76e71cf6', //REQUIRED - Amazon Cognito Identity Pool ID
        region: 'us-west-2', // REQUIRED - Amazon Cognito Region
        userPoolId: 'us-west-2_cnmvDtQtS', //OPTIONAL - Amazon Cognito User Pool ID
        userPoolWebClientId: 'k1m8k2uejmb3ii6jt27fd1fio', //OPTIONAL - Amazon Cognito Web Client ID

}


export default awsmobile;
